configName: sam_c21n_xpro_freertos
folderName: ''
format_version: v1.0
frameworkPath: ../../../../../..
processor: ATSAMC21N18A
projectName: ''
settings:
  PackageFilter: bootloader;bsp;core;crypto;cryptoauthlib;csp;micrium_ucos3;net;touch;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMC21_DFP\3.3.71\samc21n\atdf\ATSAMC21N18A.atdf
