format_version: v1.0
type: UniqueComponent
attributes: {id: drv_at25}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: DRV_AT25_CHIP_SELECT_PIN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '33'}
  - type: KeyValueSet
    attributes: {id: DRV_AT25_HOLD_PIN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '56'}
  - type: String
    attributes: {id: DRV_AT25_PLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_at25, value: SERCOM5}
  - type: KeyValueSet
    attributes: {id: DRV_AT25_WRITE_PROTECT_PIN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '20'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: drv_at25_SPI_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: sercom5}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: SERCOM5_SPI}
- type: ElementPosition
  attributes: {x: '381', y: '71', id: drv_at25}
